---
# tasks file for memcahced

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ req_dependencies }}"


- name: Update the Apt cache
  apt:
    update_cache: yes

  
- name: Download Memcached source
  get_url:
    url: "https://www.memcached.org/files/memcached-1.6.14.tar.gz"
    dest: "/tmp/memcached-1.6.14.tar.gz"
    checksum: "sha256:54d63742c6886dcdc4e0c87f4439a2930a876cd9f2bfa01d699b0c6bad1707b3"

- name: Extract Memcached source
  unarchive:
    src: "/tmp/memcached-1.6.14.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/memcached-1.6.14"


- name: Compile and Install Memcached
  shell: |
    cd /tmp/memcached-1.6.14
    ./configure
    make
    make install
  args:
    executable: /bin/bash

- name: Compile and Install Memcached
  shell: |
    cd /tmp/memcached-1.6.14
    ./configure
    make
    make install
  args:
    executable: /bin/bash

- name: Cleanup temporary files
  file:
    path: "/tmp/memcached-1.6.14"
    state: absent

- name: Copy the systemd service file using Jinja2 template
  template:
    src: memchached.service.j2
    dest: /etc/systemd/system/memcached.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Memcached